export const ErrorCodes = Object.freeze({
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  INVALID_UUID: 'INVALID_UUID',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  SOMETHING_WENT_WRONG: 'SOMETHING_WENT_WRONG'
});